### ISSUE TITLE
New release 2.0.21 breaking with UglifyJs Unexpected token: operator (>)

### ISSUE THREAD

**Issue by dhwang** [jpgorman/react-append-to-body#11]
> ERROR in 2.mdi.module.18693e2a.js from UglifyJs
> Unexpected token: operator (>) [./node_modules/react-append-to-body/dist/main.js:1,3317]

After downgrading package to 2.0.20 this error is gone.

**Comment by jpgorman** [comment]
I will take a look

**Comment by jpgorman** [comment]
I've updated the build to remove any es6 from the module. You can check this out from this commit https://github.com/jpgorman/react-append-to-body/commit/36c9bb54f41046c857359d5bd4015a6bb08c3fcb

If you have time can you try again, building the library from https://github.com/jpgorman/react-append-to-body/tree/bug/%2311

Just checkout the branch, run `$ yarn && yarn build && npm pack` then add the produced package to your project via `yarn add file: path/to/react-append-to-body.tgz`

**Comment by jpgorman** [comment]
If that fixes the issue, i'll publish a patched version

**Comment by jpgorman** [comment]
Marking as resolved in the latest release 2.0.24
