### ISSUE TITLE
"React does not recognize the `subtreeContainer` prop on a DOM element" error

### ISSUE THREAD

**Issue by clodpated** [jpgorman/react-append-to-body#20]
I'm making use of this library and it behaves as expected, but flashes this warning on each render: 

`index.js:1 Warning: React does not recognize the `subtreeContainer` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `subtreecontainer` instead. If you accidentally passed it from a parent component, remove it from the DOM element.`

![image](https://user-images.githubusercontent.com/1044715/88703879-4e66da00-d0db-11ea-9e09-f3e2b7fe1472.png)

If I rename `subtreeContainer` to something all lower case, the warning goes away. 

I could update that and just PR, but realize it could be a breaking change and I didn't want to do that without talking about it.

**Comment by jpgorman** [comment]
Thanks for raising the issue. Feel free to create a PR if you're happy to. I guess really that the subtreecContainer prop shouldn't be applied to the DOM element at all as it's not a valid HTML prop.

**Comment by clodpated** [comment]
Fair. Yeah I could just change it to something like `data-subtreecontainer` maybe?

**Comment by jpgorman** [comment]
Sure let's see how that works. PR away.
