### ISSUE TITLE
Package size

### ISSUE THREAD

**Issue by zslabs** [jpgorman/react-append-to-body#3]
Hey, thanks a lot for building this! Really helping with how we are constructing modals in our app.

I noticed that this currently increases our package size by about `400kb` when included; which is about an 80% increase on the entire styleguide (which is made up of 20 or so other components). We're re-using a lot of the same components, but it looks like there's a couple packages, `node-uuid`, `ramda` that are different than what we're already bundling. Any chance there might be some uneeded bloat behind these? It looks like the `ramda` library is mainly utilities, correct? Since a lot of projects either use [polyfill.io](https://polyfill.io) or [babel-polyfill](https://www.npmjs.com/package/babel-polyfill) nowadays, anyway we could write more native ES6 implementations of some of these utilities and let the project backfill as needed?

**Comment by jpgorman** [comment]
Ouch!! You're right, that is quick a bit extra! 

Both `Ramda` and `node-uuid` are there for convenience more than anything else. I'm more than happy to take a look and see if we can't get that bundle size down for you. Thanks for raising the issue :)

**Comment by zslabs** [comment]
Thanks man! So if you need a bit more context, I'm doing this work inside of https://github.com/rhinogram/rhinostyle and more specifically in the https://github.com/rhinogram/rhinostyle/tree/zach/modal-append-example branch. If you take a look at https://github.com/rhinogram/rhinostyle/blob/zach/modal-append-example/dist/scripts/rhinostyle.min.js (generated by running `gulp dist:scripts` that's the one that gets pretty beefy. Also https://github.com/rhinogram/rhinostyle/blob/zach/modal-append-example/build/scripts/rhinostyle-docs.js is increasing by about `1mb` if I take out your package around both `<Modal />` and `<Cover />`.

**Comment by zslabs** [comment]
I've done some optimizations around trimming up the `momentjs` bundle in the Webpack config that may skew the results compared to what's currently in `master`, but unwrapping `<Modal />` and `<Cover />` show the issue on build.

**Comment by jpgorman** [comment]
Ramda is coming in at about `683kb` looking in the `node_modules` which will most likely go up with future releases of Ramda. I'll look into how I can either reduce the Ramda bundle to only use the requisite methods or failing that, swap out those methods for their es5/6 native methods

**Comment by zslabs** [comment]
Did a little bit of digging and maybe https://github.com/ramda/ramda/issues/2161#issuecomment-301450577 might be helpful in grabbing specific pieces, but like you said, may be preferable to use native methods wherever possible and let the end-consumer do what they will to transpile those.

**Comment by zslabs** [comment]
Possibly something like `import map from 'ramda/src/map'` for example

**Comment by zslabs** [comment]
Went ahead and opened up a PR if you want to take a look ➡️

**Comment by jeanpaulgorman** [comment]
Sure, I've merged this in now. I've been thinking about this a little more and I think there are issues still to be addressed around the bundle itself. I'm going to look into creating the bundle via `Webpack` to remove `Ramda` as a dependency at all.

**Comment by zslabs** [comment]
Yeah, that sounds like a great plan! Appreciate you taking the time to review those PRs; even if it is just a bandaid for right now.

**Comment by zslabs** [comment]
In the meantime, do you think you could cut a release with those updates? Was going to just use the `master` branch in `package.json` in my project, but unfortunately installing via a repo isn't bringing over what I need to consume it (not exactly sure why, but weird).

**Comment by jeanpaulgorman** [comment]
Sure I'll take a take a look when I finish work

**Comment by jpgorman** [comment]
I've released an update version now 2.0.3

**Comment by zslabs** [comment]
Thanks!

**Comment by jpgorman** [comment]
Let me know if it sorts the issue for you

**Comment by zslabs** [comment]
Still adding quite a lot unfortunately. I've taken out the `momentjs` cleanup so we can see a comparison.

If you look at https://github.com/rhinogram/rhinostyle/blob/master/dist/scripts/rhinostyle.min.js (current master) you'll see it weighs in at about `695 KB`

If you look at that new branch with this package, https://github.com/rhinogram/rhinostyle/blob/zach/modal-append-example/dist/scripts/rhinostyle.min.js it jumps to `996 KB`

If (locally) I remove the wrappers and inclusions of this package (to make sure there's nothing else impacting this branch), `rhinostyle.min.js` becomes `682 KB` (the difference being I was able to delete a couple files from how it was done previously).

It seems like those array methods (I think) are still unfortunately causing excess page-weight.

**Comment by jeanpaulgorman** [comment]
Okay no worries, I'll work on refactoring out Ramda

**Comment by jeanpaulgorman** [comment]
Just FYI, I did build out a test package using `webpack` last night after the recent changes which got the bundle down to 161kb.

**Comment by jeanpaulgorman** [comment]
That was done by keeping `React` as an external dependency, from the build.

**Comment by jeanpaulgorman** [comment]
I'm going to start by looking to swap out `Ramda` with this package, which seems to have be created for sole reason of reducing the package size associated with `Ramda`.

https://github.com/selfrefactor/rambda

**Comment by jeanpaulgorman** [comment]
Okay, I've created a new branch with `Ramda` completely removed once the tests pass I'll merge it into master and cut a new release. The replacement Library `Rambda` is only 10 kb in size so this should resolve the issue for you.

**Comment by zslabs** [comment]
👍 Having a little trouble seeing the compiled code within my project (linking it over from the branch I have pulled down), but definitely worth a shot if the tests pass. Do you think https://github.com/jpgorman/react-append-to-body/issues/8 could also be contributing? I do remember seeing some extra code in there for a "node buffer" (or something like that).

**Comment by jeanpaulgorman** [comment]
#8 won't be having an effect yet as that issue is still outstanding

**Comment by zslabs** [comment]
Sorry - to clarify, meant on if the different builds not being there could contribute to the size inflation. Reading that ticket that's exactly what you're talking about, so yeah it'd be interesting to test releasing this smaller array package to determine if that'll solve things.

**Comment by jpgorman** [comment]
I've just released version 2.0.4 now which uses `rambda`. I've created a test build locally that comes out at 35kb unminified.

**Comment by zslabs** [comment]
Is this being exported differently (as ES6) now? For some reason my Uglifier is freaking out and won't compile. Switching back to `2.02` works fine though.

**Comment by jpgorman** [comment]
ahh yes I just ran into this, it's because the `rambda` library is compiled to es6..... sigh

**Comment by jpgorman** [comment]
Here's a possible work around : https://www.npmjs.com/package/uglifyjs-webpack-plugin

**Comment by zslabs** [comment]
Hm yeah, are ya thinking of providing a `dist/` by default that has this already done as part of your build script? I don't necessarily have an issue with including this package as part of the files to run through my compiler, but I've seen some pushback in other libs about having to make exceptions for things like this instead of just including a built ES5 file with it.

**Comment by jpgorman** [comment]
You can resolve the Uglification issue by using `webpack-uglify-harmony`

Then in your production config, you can use 
`var UglifyJSPlugin = require('webpack-uglify-harmony')`

**Comment by jpgorman** [comment]
Yes, I'm going to provide an es5 /dist so that issue, like this can be avoided. I'll get to it asap.

**Comment by zslabs** [comment]
Thanks man - really appreciate you digging into this with me on this over the past few days.

**Comment by jpgorman** [comment]
As a quick fix for now, I'm just going to convert everything to es5 for the build. It's not a minified compiled version though

**Comment by jpgorman** [comment]
ok i've done that now, check version 2.0.7 and see if your build is smaller

**Comment by zslabs** [comment]
🎉 That did it! 🎉

**Comment by jpgorman** [comment]
whoop :)
