### ISSUE TITLE
PropTypes package

### ISSUE THREAD

**Issue by zslabs** [jpgorman/react-append-to-body#5]
Hey,
Have any thoughts on updating the dep requirement version of React to `15.5.[LATEST]`? Along with that, it's preferable to also update to using the [prop-types](https://www.npmjs.com/package/prop-types) package (from [this release post](https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html)). Currently if this is used in projects using newer version of React; they'll get warnings about the deprecation.

**Comment by jeanpaulgorman** [comment]
Yup, I was just thinking about that as it happens. As React is at 15.6.x I'm quite happy to do that, with a major bump so that people using older versions of react can still be supported.

**Comment by zslabs** [comment]
Nice! Just a quick note; users of older versions of React will still be able to use this package just the same; as the `prop-types` package should have complete parity to what is currently being used here for the prop type declaration you have. I'm happy to submit a PR for this unless you're already tackling while you're looking at https://github.com/jpgorman/react-append-to-body/issues/3

**Comment by jeanpaulgorman** [comment]
Sure, feel free to submit a PR

**Comment by zslabs** [comment]
Went ahead and opened up a PR if you want to take a look ➡️
